"""add groups metadata, reactions, attachments

Revision ID: 34101a7fcf31
Revises: 07eadc41c2f5
Create Date: 2026-07-27 21:15:23.614385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34101a7fcf31'
down_revision: Union[str, Sequence[str], None] = '07eadc41c2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('chat_message_reactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_message_user_emoji')
    )
    op.create_index(op.f('ix_chat_message_reactions_user_id'), 'chat_message_reactions', ['user_id'], unique=False)
    op.add_column('chat_conversations', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('chat_conversations', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('chat_messages', 'message_type',
               existing_type=mysql.ENUM('TEXT', 'SYSTEM'),
               type_=sa.Enum('TEXT', 'SYSTEM', 'IMAGE', 'FILE', name='messagetype'),
               existing_nullable=False)
    op.add_column('chat_participants', sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='participantrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'role')
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.Enum('TEXT', 'SYSTEM', 'IMAGE', 'FILE', name='messagetype'),
               type_=mysql.ENUM('TEXT', 'SYSTEM'),
               existing_nullable=False)
    op.drop_column('chat_conversations', 'description')
    op.drop_column('chat_conversations', 'avatar_url')
    op.drop_index(op.f('ix_chat_message_reactions_user_id'), table_name='chat_message_reactions')
    op.drop_table('chat_message_reactions')
    op.drop_table('chat_attachments')
    # ### end Alembic commands ###
