"""Add timestamps to chat tables

Revision ID: 45843ebb0ebe
Revises: 34101a7fcf31
Create Date: 2026-07-27 22:05:13.813413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45843ebb0ebe'
down_revision: Union[str, Sequence[str], None] = '34101a7fcf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_attachments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('chat_message_reactions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('chat_participants', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('chat_participants', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'updated_at')
    op.drop_column('chat_participants', 'created_at')
    op.drop_column('chat_message_reactions', 'updated_at')
    op.drop_column('chat_attachments', 'updated_at')
    # ### end Alembic commands ###
