"""Add indexing for conversations and participants

Revision ID: ea77cd3ccdb0
Revises: 45843ebb0ebe
Create Date: 2026-07-29 22:31:49.114458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea77cd3ccdb0'
down_revision: Union[str, Sequence[str], None] = '45843ebb0ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_conversations_org_type', 'chat_conversations', ['organization_id', 'type'], unique=False)
    op.create_unique_constraint('uix_chat_participant_conv_user', 'chat_participants', ['conversation_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_chat_participant_conv_user', 'chat_participants', type_='unique')
    op.drop_index('ix_chat_conversations_org_type', table_name='chat_conversations')
    # ### end Alembic commands ###
